#!/usr/bin/env python3
"""Comprehensive test suite for generate_sbom tool and CLI subcommand."""

from __future__ import annotations

import json
from unittest.mock import patch

import pytest

from manus_agent.tools.generate_sbom import (
    TOOL_SPEC,
    _build_cyclonedx,
    _make_purl,
    _parse_cargo,
    _parse_gemfile,
    _parse_gosum,
    _parse_npm,
    _parse_pnpm,
    _parse_poetry,
    _parse_requirements,
    _parse_yarn,
    _purl_encode,
    detect_lockfile_type,
    generate_sbom,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture
def tool_use():
    return {"toolUseId": "test-123"}


@pytest.fixture
def npm_v3_lockfile():
    return json.dumps(
        {
            "name": "my-app",
            "lockfileVersion": 3,
            "packages": {
                "": {"name": "my-app", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.21"},
                "node_modules/@babel/core": {
                    "name": "@babel/core",
                    "version": "7.24.0",
                },
                "node_modules/@types/node": {
                    "name": "@types/node",
                    "version": "20.11.0",
                },
            },
        }
    )


@pytest.fixture
def npm_v1_lockfile():
    return json.dumps(
        {
            "name": "legacy-app",
            "lockfileVersion": 1,
            "dependencies": {
                "express": {
                    "version": "4.18.2",
                    "dependencies": {
                        "body-parser": {"version": "1.20.2"},
                    },
                },
                "@scope/pkg": {"version": "2.0.0"},
            },
        }
    )


@pytest.fixture
def yarn_lockfile():
    return """\
# yarn lockfile v1

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@babel/core@^7.0.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz"

express@^4.18.0, express@^4.17.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
"""


@pytest.fixture
def pnpm_lockfile():
    return """\
lockfileVersion: '6.0'

packages:

  /lodash@4.17.21:
    resolution: {integrity: sha512-abc}
    dev: false

  /@babel/core@7.24.0:
    resolution: {integrity: sha512-def}
    dev: true

  /express@4.18.2:
    resolution: {integrity: sha512-ghi}
    dev: false
"""


@pytest.fixture
def pnpm_v9_lockfile():
    return """\
lockfileVersion: '9.0'

packages:

  lodash@4.17.21:
    resolution: {integrity: sha512-abc}

  '@babel/core@7.24.0':
    resolution: {integrity: sha512-def}
"""


@pytest.fixture
def poetry_lockfile():
    return """\
[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."

[[package]]
name = "flask"
version = "3.0.0"
description = "A micro web framework."

[[package]]
name = "urllib3"
version = "2.1.0"
description = "HTTP library."
"""


@pytest.fixture
def requirements_lockfile():
    return """\
# This is a comment
requests==2.31.0
flask==3.0.0
urllib3[socks]==2.1.0
-r other.txt
numpy==1.26.3
# unpinned (skipped)
boto3>=1.0
"""


@pytest.fixture
def gosum_lockfile():
    return """\
github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=
github.com/pkg/errors v0.9.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
golang.org/x/sys v0.15.0 h1:h48lPFYpsTvQJZF4EKyI4aLHaev3CxivZmv7yZig9pc=
golang.org/x/sys v0.15.0/go.mod h1:/VUhepiaJMQUp4+oa/7Zr1D23ma6VTLIYjOOTFZPUcA=
github.com/stretchr/testify v1.8.4 h1:CcVxjf3Q8PM0mHUKJCdn+eZZtm5yQksXRJi6DN2o+HA=
"""


@pytest.fixture
def cargo_lockfile():
    return """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.195"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.35.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "my-crate"
version = "0.1.0"
"""


@pytest.fixture
def gemfile_lockfile():
    return """\
GEM
  remote: https://rubygems.org/
  specs:
    rails (7.1.2)
    nokogiri (1.16.0)
      mini_portile2 (~> 2.8.5)
    mini_portile2 (2.8.5)

PLATFORMS
  ruby
  x86_64-linux

BUNDLED WITH
   2.5.3
"""


# ---------------------------------------------------------------------------
# TOOL_SPEC tests
# ---------------------------------------------------------------------------
class TestToolSpec:
    def test_tool_spec_name(self):
        assert TOOL_SPEC["name"] == "generate_sbom"

    def test_tool_spec_has_description(self):
        assert "CycloneDX" in TOOL_SPEC["description"]
        assert "lockfile" in TOOL_SPEC["description"]

    def test_tool_spec_input_schema(self):
        schema = TOOL_SPEC["inputSchema"]["json"]
        assert schema["type"] == "object"
        assert "lockfile_path" in schema["properties"]
        assert "lockfile_content" in schema["properties"]
        assert "lockfile_type" in schema["properties"]

    def test_tool_spec_lockfile_type_enum(self):
        schema = TOOL_SPEC["inputSchema"]["json"]
        enum_vals = schema["properties"]["lockfile_type"]["enum"]
        assert "npm" in enum_vals
        assert "poetry" in enum_vals
        assert "cargo" in enum_vals
        assert "gosum" in enum_vals


# ---------------------------------------------------------------------------
# Purl helper tests
# ---------------------------------------------------------------------------
class TestPurlHelpers:
    def test_purl_encode_basic(self):
        assert _purl_encode("simple") == "simple"

    def test_purl_encode_at_sign(self):
        assert _purl_encode("a@b") == "a%40b"

    def test_purl_encode_slash(self):
        assert _purl_encode("a/b") == "a%2Fb"

    def test_make_purl_npm(self):
        result = _make_purl("npm", "lodash", "4.17.21")
        assert result == "pkg:npm/lodash@4.17.21"

    def test_make_purl_npm_scoped(self):
        result = _make_purl("npm", "core", "7.24.0", namespace="@babel")
        assert result == "pkg:npm/%40babel/core@7.24.0"

    def test_make_purl_pypi(self):
        result = _make_purl("poetry", "requests", "2.31.0")
        assert result == "pkg:pypi/requests@2.31.0"

    def test_make_purl_cargo(self):
        result = _make_purl("cargo", "serde", "1.0.195")
        assert result == "pkg:cargo/serde@1.0.195"

    def test_make_purl_golang(self):
        result = _make_purl("gosum", "errors", "0.9.1", namespace="github.com/pkg")
        assert result == "pkg:golang/github.com%2Fpkg/errors@0.9.1"

    def test_make_purl_gem(self):
        result = _make_purl("gemfile", "rails", "7.1.2")
        assert result == "pkg:gem/rails@7.1.2"


# ---------------------------------------------------------------------------
# Parser tests — npm
# ---------------------------------------------------------------------------
class TestParseNpm:
    def test_npm_v3_basic(self, npm_v3_lockfile):
        components = _parse_npm(npm_v3_lockfile)
        names = {c[0] for c in components}
        assert "lodash" in names
        assert "@babel/core" in names
        assert "@types/node" in names

    def test_npm_v3_skips_root(self, npm_v3_lockfile):
        components = _parse_npm(npm_v3_lockfile)
        names = {c[0] for c in components}
        assert "my-app" not in names

    def test_npm_v3_versions(self, npm_v3_lockfile):
        components = _parse_npm(npm_v3_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["lodash"] == "4.17.21"
        assert versions["@babel/core"] == "7.24.0"

    def test_npm_v3_purls(self, npm_v3_lockfile):
        components = _parse_npm(npm_v3_lockfile)
        purls = {c[0]: c[2] for c in components}
        assert purls["lodash"] == "pkg:npm/lodash@4.17.21"
        assert "pkg:npm/%40babel/core@7.24.0" == purls["@babel/core"]

    def test_npm_v1_basic(self, npm_v1_lockfile):
        components = _parse_npm(npm_v1_lockfile)
        names = {c[0] for c in components}
        assert "express" in names
        assert "body-parser" in names
        assert "@scope/pkg" in names

    def test_npm_v1_nested(self, npm_v1_lockfile):
        components = _parse_npm(npm_v1_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["body-parser"] == "1.20.2"

    def test_npm_invalid_json(self):
        components = _parse_npm("not valid json {{{")
        assert components == []

    def test_npm_empty_packages(self):
        data = json.dumps({"lockfileVersion": 3, "packages": {}})
        components = _parse_npm(data)
        assert components == []

    def test_npm_deduplication(self):
        data = json.dumps(
            {
                "lockfileVersion": 1,
                "dependencies": {
                    "lodash": {"version": "4.17.21"},
                },
                "packages": {
                    "": {},
                    "node_modules/lodash": {"version": "4.17.21"},
                },
            }
        )
        components = _parse_npm(data)
        # v2/v3 packages is preferred, only one entry
        assert len(components) == 1


# ---------------------------------------------------------------------------
# Parser tests — yarn
# ---------------------------------------------------------------------------
class TestParseYarn:
    def test_yarn_basic(self, yarn_lockfile):
        components = _parse_yarn(yarn_lockfile)
        names = {c[0] for c in components}
        assert "lodash" in names
        assert "@babel/core" in names
        assert "express" in names

    def test_yarn_versions(self, yarn_lockfile):
        components = _parse_yarn(yarn_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["lodash"] == "4.17.21"
        assert versions["express"] == "4.18.2"

    def test_yarn_scoped_purl(self, yarn_lockfile):
        components = _parse_yarn(yarn_lockfile)
        purls = {c[0]: c[2] for c in components}
        assert "%40babel" in purls["@babel/core"]

    def test_yarn_deduplication(self, yarn_lockfile):
        # express appears twice in header but should deduplicate
        components = _parse_yarn(yarn_lockfile)
        express_entries = [c for c in components if c[0] == "express"]
        assert len(express_entries) == 1

    def test_yarn_empty(self):
        components = _parse_yarn("# empty yarn.lock\n")
        assert components == []


# ---------------------------------------------------------------------------
# Parser tests — pnpm
# ---------------------------------------------------------------------------
class TestParsePnpm:
    def test_pnpm_v6_basic(self, pnpm_lockfile):
        components = _parse_pnpm(pnpm_lockfile)
        names = {c[0] for c in components}
        assert "lodash" in names
        assert "@babel/core" in names
        assert "express" in names

    def test_pnpm_v6_versions(self, pnpm_lockfile):
        components = _parse_pnpm(pnpm_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["lodash"] == "4.17.21"
        assert versions["@babel/core"] == "7.24.0"

    def test_pnpm_v9_format(self, pnpm_v9_lockfile):
        components = _parse_pnpm(pnpm_v9_lockfile)
        names = {c[0] for c in components}
        assert "lodash" in names
        assert "@babel/core" in names

    def test_pnpm_empty(self):
        components = _parse_pnpm("lockfileVersion: '6.0'\n")
        assert components == []

    def test_pnpm_ecosystem_is_npm(self, pnpm_lockfile):
        components = _parse_pnpm(pnpm_lockfile)
        for comp in components:
            assert comp[3] == "npm"


# ---------------------------------------------------------------------------
# Parser tests — poetry
# ---------------------------------------------------------------------------
class TestParsePoetry:
    def test_poetry_basic(self, poetry_lockfile):
        components = _parse_poetry(poetry_lockfile)
        names = {c[0] for c in components}
        assert "requests" in names
        assert "flask" in names
        assert "urllib3" in names

    def test_poetry_versions(self, poetry_lockfile):
        components = _parse_poetry(poetry_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["requests"] == "2.31.0"
        assert versions["flask"] == "3.0.0"

    def test_poetry_purl_normalization(self, poetry_lockfile):
        # PyPI names are normalized to lowercase with hyphens
        components = _parse_poetry(poetry_lockfile)
        purls = {c[0]: c[2] for c in components}
        assert purls["requests"] == "pkg:pypi/requests@2.31.0"

    def test_poetry_underscore_normalization(self):
        content = '[[package]]\nname = "my_package"\nversion = "1.0.0"\n'
        components = _parse_poetry(content)
        assert components[0][2] == "pkg:pypi/my-package@1.0.0"

    def test_poetry_ecosystem(self, poetry_lockfile):
        components = _parse_poetry(poetry_lockfile)
        for comp in components:
            assert comp[3] == "pypi"

    def test_poetry_empty(self):
        components = _parse_poetry("")
        assert components == []


# ---------------------------------------------------------------------------
# Parser tests — requirements.txt
# ---------------------------------------------------------------------------
class TestParseRequirements:
    def test_requirements_basic(self, requirements_lockfile):
        components = _parse_requirements(requirements_lockfile)
        names = {c[0] for c in components}
        assert "requests" in names
        assert "flask" in names
        assert "numpy" in names

    def test_requirements_skips_unpinned(self, requirements_lockfile):
        components = _parse_requirements(requirements_lockfile)
        names = {c[0] for c in components}
        assert "boto3" not in names

    def test_requirements_skips_comments(self, requirements_lockfile):
        components = _parse_requirements(requirements_lockfile)
        # 4 pinned packages
        assert len(components) == 4

    def test_requirements_handles_extras(self, requirements_lockfile):
        components = _parse_requirements(requirements_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["urllib3"] == "2.1.0"

    def test_requirements_empty(self):
        components = _parse_requirements("# nothing here\n")
        assert components == []


# ---------------------------------------------------------------------------
# Parser tests — go.sum
# ---------------------------------------------------------------------------
class TestParseGosum:
    def test_gosum_basic(self, gosum_lockfile):
        components = _parse_gosum(gosum_lockfile)
        names = {c[0] for c in components}
        assert "github.com/pkg/errors" in names
        assert "golang.org/x/sys" in names
        assert "github.com/stretchr/testify" in names

    def test_gosum_deduplication(self, gosum_lockfile):
        # go.sum has both h1: and /go.mod lines — should deduplicate
        components = _parse_gosum(gosum_lockfile)
        error_entries = [c for c in components if c[0] == "github.com/pkg/errors"]
        assert len(error_entries) == 1

    def test_gosum_version_stripped(self, gosum_lockfile):
        components = _parse_gosum(gosum_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["github.com/pkg/errors"] == "0.9.1"
        assert versions["golang.org/x/sys"] == "0.15.0"

    def test_gosum_purl_format(self, gosum_lockfile):
        components = _parse_gosum(gosum_lockfile)
        purls = {c[0]: c[2] for c in components}
        assert "pkg:golang/github.com/pkg/errors@0.9.1" == purls["github.com/pkg/errors"]

    def test_gosum_ecosystem(self, gosum_lockfile):
        components = _parse_gosum(gosum_lockfile)
        for comp in components:
            assert comp[3] == "golang"

    def test_gosum_empty(self):
        components = _parse_gosum("")
        assert components == []


# ---------------------------------------------------------------------------
# Parser tests — Cargo.lock
# ---------------------------------------------------------------------------
class TestParseCargo:
    def test_cargo_basic(self, cargo_lockfile):
        components = _parse_cargo(cargo_lockfile)
        names = {c[0] for c in components}
        assert "serde" in names
        assert "tokio" in names
        assert "my-crate" in names

    def test_cargo_versions(self, cargo_lockfile):
        components = _parse_cargo(cargo_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["serde"] == "1.0.195"
        assert versions["tokio"] == "1.35.1"

    def test_cargo_purl(self, cargo_lockfile):
        components = _parse_cargo(cargo_lockfile)
        purls = {c[0]: c[2] for c in components}
        assert purls["serde"] == "pkg:cargo/serde@1.0.195"

    def test_cargo_ecosystem(self, cargo_lockfile):
        components = _parse_cargo(cargo_lockfile)
        for comp in components:
            assert comp[3] == "crates.io"

    def test_cargo_empty(self):
        components = _parse_cargo("")
        assert components == []


# ---------------------------------------------------------------------------
# Parser tests — Gemfile.lock
# ---------------------------------------------------------------------------
class TestParseGemfile:
    def test_gemfile_basic(self, gemfile_lockfile):
        components = _parse_gemfile(gemfile_lockfile)
        names = {c[0] for c in components}
        assert "rails" in names
        assert "nokogiri" in names
        assert "mini_portile2" in names

    def test_gemfile_versions(self, gemfile_lockfile):
        components = _parse_gemfile(gemfile_lockfile)
        versions = {c[0]: c[1] for c in components}
        assert versions["rails"] == "7.1.2"
        assert versions["nokogiri"] == "1.16.0"

    def test_gemfile_purl(self, gemfile_lockfile):
        components = _parse_gemfile(gemfile_lockfile)
        purls = {c[0]: c[2] for c in components}
        assert purls["rails"] == "pkg:gem/rails@7.1.2"

    def test_gemfile_ecosystem(self, gemfile_lockfile):
        components = _parse_gemfile(gemfile_lockfile)
        for comp in components:
            assert comp[3] == "rubygems"

    def test_gemfile_empty(self):
        components = _parse_gemfile("")
        assert components == []


# ---------------------------------------------------------------------------
# Format detection tests
# ---------------------------------------------------------------------------
class TestDetectLockfileType:
    def test_npm(self):
        assert detect_lockfile_type("package-lock.json") == "npm"

    def test_npm_shrinkwrap(self):
        assert detect_lockfile_type("npm-shrinkwrap.json") == "npm"

    def test_yarn(self):
        assert detect_lockfile_type("yarn.lock") == "yarn"

    def test_pnpm(self):
        assert detect_lockfile_type("pnpm-lock.yaml") == "pnpm"

    def test_poetry(self):
        assert detect_lockfile_type("poetry.lock") == "poetry"

    def test_requirements(self):
        assert detect_lockfile_type("requirements.txt") == "requirements"

    def test_gosum(self):
        assert detect_lockfile_type("go.sum") == "gosum"

    def test_cargo(self):
        assert detect_lockfile_type("Cargo.lock") == "cargo"

    def test_gemfile(self):
        assert detect_lockfile_type("Gemfile.lock") == "gemfile"

    def test_unknown(self):
        assert detect_lockfile_type("random.txt") is None

    def test_path_with_dirs(self):
        assert detect_lockfile_type("/some/path/package-lock.json") == "npm"


# ---------------------------------------------------------------------------
# CycloneDX builder tests
# ---------------------------------------------------------------------------
class TestBuildCyclonedx:
    def test_spec_version(self):
        sbom = _build_cyclonedx([])
        assert sbom["specVersion"] == "1.5"

    def test_bom_format(self):
        sbom = _build_cyclonedx([])
        assert sbom["bomFormat"] == "CycloneDX"

    def test_serial_number(self):
        sbom = _build_cyclonedx([("pkg", "1.0", "pkg:npm/pkg@1.0", "npm")])
        assert sbom["serialNumber"].startswith("urn:uuid:")

    def test_deterministic_serial(self):
        components = [("a", "1.0", "pkg:npm/a@1.0", "npm")]
        sbom1 = _build_cyclonedx(components)
        sbom2 = _build_cyclonedx(components)
        assert sbom1["serialNumber"] == sbom2["serialNumber"]

    def test_different_content_different_serial(self):
        sbom1 = _build_cyclonedx([("a", "1.0", "pkg:npm/a@1.0", "npm")])
        sbom2 = _build_cyclonedx([("b", "2.0", "pkg:npm/b@2.0", "npm")])
        assert sbom1["serialNumber"] != sbom2["serialNumber"]

    def test_metadata_project_name(self):
        sbom = _build_cyclonedx([], project_name="my-project")
        assert sbom["metadata"]["component"]["name"] == "my-project"

    def test_metadata_tool(self):
        sbom = _build_cyclonedx([])
        tools = sbom["metadata"]["tools"]
        assert any(t["name"] == "generate_sbom" for t in tools)

    def test_components_sorted(self):
        components = [
            ("zlib", "1.0", "pkg:npm/zlib@1.0", "npm"),
            ("axios", "2.0", "pkg:npm/axios@2.0", "npm"),
        ]
        sbom = _build_cyclonedx(components)
        assert sbom["components"][0]["name"] == "axios"
        assert sbom["components"][1]["name"] == "zlib"

    def test_component_structure(self):
        components = [("lodash", "4.17.21", "pkg:npm/lodash@4.17.21", "npm")]
        sbom = _build_cyclonedx(components)
        comp = sbom["components"][0]
        assert comp["type"] == "library"
        assert comp["name"] == "lodash"
        assert comp["version"] == "4.17.21"
        assert comp["purl"] == "pkg:npm/lodash@4.17.21"

    def test_lockfile_path_in_properties(self):
        sbom = _build_cyclonedx([], lockfile_path="/app/package-lock.json")
        props = sbom["metadata"]["component"]["properties"]
        assert any(p["value"] == "/app/package-lock.json" for p in props)

    def test_empty_components(self):
        sbom = _build_cyclonedx([])
        assert sbom["components"] == []


# ---------------------------------------------------------------------------
# Main generate_sbom tool function tests
# ---------------------------------------------------------------------------
class TestGenerateSbomTool:
    def test_from_file_path(self, tool_use, tmp_path):
        lockfile = tmp_path / "package-lock.json"
        lockfile.write_text(
            json.dumps(
                {
                    "lockfileVersion": 3,
                    "packages": {
                        "": {},
                        "node_modules/lodash": {"version": "4.17.21"},
                    },
                }
            )
        )
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "success"
        assert "1 components" in result["content"][0]["text"]

    def test_from_content(self, tool_use):
        content = '[[package]]\nname = "requests"\nversion = "2.31.0"\n'
        result = generate_sbom(
            tool_use,
            lockfile_content=content,
            lockfile_type="poetry",
        )
        assert result["status"] == "success"
        assert "1 components" in result["content"][0]["text"]

    def test_file_not_found(self, tool_use):
        result = generate_sbom(tool_use, lockfile_path="/nonexistent/file.json")
        assert result["status"] == "error"
        assert "not found" in result["content"][0]["text"]

    def test_no_input(self, tool_use):
        result = generate_sbom(tool_use)
        assert result["status"] == "error"
        assert "must be provided" in result["content"][0]["text"]

    def test_unknown_type(self, tool_use):
        result = generate_sbom(tool_use, lockfile_content="data", lockfile_type="")
        # No type and no path to detect from
        assert result["status"] == "error"

    def test_unsupported_type(self, tool_use, tmp_path):
        lockfile = tmp_path / "unknown.xyz"
        lockfile.write_text("content")
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "error"
        assert "Cannot detect" in result["content"][0]["text"]

    def test_content_with_type(self, tool_use):
        content = "serde 1.0.195\ntokio 1.35.1\n"
        # This isn't valid cargo format, should return empty SBOM
        result = generate_sbom(tool_use, lockfile_content=content, lockfile_type="cargo")
        assert result["status"] == "success"
        assert "0 components" in result["content"][0]["text"]

    def test_project_name_override(self, tool_use, tmp_path):
        lockfile = tmp_path / "poetry.lock"
        lockfile.write_text('[[package]]\nname = "requests"\nversion = "2.31.0"\n')
        result = generate_sbom(
            tool_use,
            lockfile_path=str(lockfile),
            project_name="custom-project",
        )
        assert result["status"] == "success"
        sbom_text = result["content"][0]["text"]
        assert "custom-project" in sbom_text

    def test_output_is_valid_json(self, tool_use, tmp_path):
        lockfile = tmp_path / "Cargo.lock"
        lockfile.write_text('[[package]]\nname = "serde"\nversion = "1.0.195"\n')
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "success"
        text = result["content"][0]["text"]
        # Extract JSON from after the summary line
        json_start = text.index("{")
        json_str = text[json_start:]
        parsed = json.loads(json_str)
        assert parsed["bomFormat"] == "CycloneDX"

    def test_read_error(self, tool_use, tmp_path):
        lockfile = tmp_path / "package-lock.json"
        lockfile.write_text("data")
        lockfile.chmod(0o000)
        try:
            result = generate_sbom(tool_use, lockfile_path=str(lockfile))
            assert result["status"] == "error"
            assert "Failed to read" in result["content"][0]["text"]
        finally:
            lockfile.chmod(0o644)


# ---------------------------------------------------------------------------
# CLI subcommand tests
# ---------------------------------------------------------------------------
class TestCliGenerateSbom:
    def test_cli_json_output(self, tmp_path):
        lockfile = tmp_path / "poetry.lock"
        lockfile.write_text('[[package]]\nname = "flask"\nversion = "3.0.0"\n')

        from manus_agent.cli import _run_generate_sbom

        with patch("builtins.print") as mock_print:
            exit_code = _run_generate_sbom([str(lockfile)])
        assert exit_code == 0
        # Check that JSON was printed
        printed = mock_print.call_args[0][0]
        parsed = json.loads(printed)
        assert parsed["bomFormat"] == "CycloneDX"
        assert len(parsed["components"]) == 1

    def test_cli_text_output(self, tmp_path):
        lockfile = tmp_path / "poetry.lock"
        lockfile.write_text('[[package]]\nname = "flask"\nversion = "3.0.0"\n')

        from manus_agent.cli import _run_generate_sbom

        with patch("builtins.print") as mock_print:
            exit_code = _run_generate_sbom([str(lockfile), "--output", "text"])
        assert exit_code == 0
        printed = mock_print.call_args[0][0]
        assert "Components:" in printed
        assert "flask" in printed

    def test_cli_out_file(self, tmp_path):
        lockfile = tmp_path / "Cargo.lock"
        lockfile.write_text('[[package]]\nname = "serde"\nversion = "1.0.0"\n')
        out_file = tmp_path / "bom.json"

        from manus_agent.cli import _run_generate_sbom

        with patch("builtins.print"):
            exit_code = _run_generate_sbom([str(lockfile), "--out-file", str(out_file)])
        assert exit_code == 0
        assert out_file.exists()
        parsed = json.loads(out_file.read_text())
        assert parsed["bomFormat"] == "CycloneDX"

    def test_cli_type_override(self, tmp_path):
        lockfile = tmp_path / "deps.txt"
        lockfile.write_text("requests==2.31.0\n")

        from manus_agent.cli import _run_generate_sbom

        with patch("builtins.print") as mock_print:
            exit_code = _run_generate_sbom([str(lockfile), "--type", "requirements"])
        assert exit_code == 0
        printed = mock_print.call_args[0][0]
        parsed = json.loads(printed)
        assert len(parsed["components"]) == 1

    def test_cli_project_name(self, tmp_path):
        lockfile = tmp_path / "go.sum"
        lockfile.write_text("github.com/pkg/errors v0.9.1 h1:abc=\n")

        from manus_agent.cli import _run_generate_sbom

        with patch("builtins.print") as mock_print:
            exit_code = _run_generate_sbom([str(lockfile), "--project-name", "my-svc"])
        assert exit_code == 0
        printed = mock_print.call_args[0][0]
        parsed = json.loads(printed)
        assert parsed["metadata"]["component"]["name"] == "my-svc"

    def test_cli_file_not_found(self):
        from manus_agent.cli import _run_generate_sbom

        with patch("builtins.print"):
            exit_code = _run_generate_sbom(["/nonexistent/file.lock"])
        assert exit_code == 1

    def test_cli_unknown_type(self, tmp_path):
        lockfile = tmp_path / "unknown.xyz"
        lockfile.write_text("data")

        from manus_agent.cli import _run_generate_sbom

        with patch("builtins.print"):
            exit_code = _run_generate_sbom([str(lockfile)])
        assert exit_code == 1

    def test_cli_in_subcommands(self):
        from manus_agent.cli import _SUBCOMMANDS

        assert "generate-sbom" in _SUBCOMMANDS


# ---------------------------------------------------------------------------
# Integration / end-to-end tests
# ---------------------------------------------------------------------------
class TestEndToEnd:
    def test_full_npm_pipeline(self, npm_v3_lockfile, tool_use, tmp_path):
        lockfile = tmp_path / "package-lock.json"
        lockfile.write_text(npm_v3_lockfile)
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "success"
        text = result["content"][0]["text"]
        json_start = text.index("{")
        sbom = json.loads(text[json_start:])
        assert sbom["specVersion"] == "1.5"
        assert len(sbom["components"]) == 3
        # Check purl format
        for comp in sbom["components"]:
            assert comp["purl"].startswith("pkg:npm/")

    def test_full_poetry_pipeline(self, poetry_lockfile, tool_use, tmp_path):
        lockfile = tmp_path / "poetry.lock"
        lockfile.write_text(poetry_lockfile)
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "success"
        text = result["content"][0]["text"]
        json_start = text.index("{")
        sbom = json.loads(text[json_start:])
        assert len(sbom["components"]) == 3
        for comp in sbom["components"]:
            assert comp["purl"].startswith("pkg:pypi/")

    def test_full_cargo_pipeline(self, cargo_lockfile, tool_use, tmp_path):
        lockfile = tmp_path / "Cargo.lock"
        lockfile.write_text(cargo_lockfile)
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "success"
        text = result["content"][0]["text"]
        json_start = text.index("{")
        sbom = json.loads(text[json_start:])
        assert len(sbom["components"]) == 3
        for comp in sbom["components"]:
            assert comp["purl"].startswith("pkg:cargo/")

    def test_full_gosum_pipeline(self, gosum_lockfile, tool_use, tmp_path):
        lockfile = tmp_path / "go.sum"
        lockfile.write_text(gosum_lockfile)
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "success"
        text = result["content"][0]["text"]
        json_start = text.index("{")
        sbom = json.loads(text[json_start:])
        assert len(sbom["components"]) == 3
        for comp in sbom["components"]:
            assert comp["purl"].startswith("pkg:golang/")

    def test_full_gemfile_pipeline(self, gemfile_lockfile, tool_use, tmp_path):
        lockfile = tmp_path / "Gemfile.lock"
        lockfile.write_text(gemfile_lockfile)
        result = generate_sbom(tool_use, lockfile_path=str(lockfile))
        assert result["status"] == "success"
        text = result["content"][0]["text"]
        json_start = text.index("{")
        sbom = json.loads(text[json_start:])
        assert len(sbom["components"]) == 3
        for comp in sbom["components"]:
            assert comp["purl"].startswith("pkg:gem/")
